---
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################
#######################         Jobs below are used to build only             #########################################
#######################        master  branches for all containers            #########################################
#######################                                                       #########################################
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

# This pipeline would be used after each merge request to build dfine latest docker images
kind: pipeline
type: docker
name: DFINE LS_dfine_latest

platform:
  arch: amd64
  os: linux

trigger:
  branch:
    - main
  event:
    - push

clone:
  depth: 1

steps:
  - name: Build latest DFINE docker image
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
      GITHUB_TOKEN_DEIM:
        from_secret: GITHUB_ACCESS_TOKEN
    settings:
      dockerfile: Dockerfile
      registry: quay.io
      repo: quay.io/logivations/ml_all
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      build_args_from_env:
        - GITHUB_TOKEN_DEIM
      cache_from: quay.io/logivations/ml_all:LS_dfine_latest
      tags:
        - LS_dfine_latest
        - LS_dfine_latest_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD

#######################################################################################################################
#######################################################################################################################
#######################################################################################################################
#######################              Jobs below are used to run               #########################################
#######################             pull request validation only              #########################################
#######################                                                       #########################################
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

# 2. Build  PR docker image for dfine
---
kind: pipeline
type: docker
name: PR validation build dfine images

platform:
  arch: amd64
  os: linux

trigger:
  event:
    include:
      - pull_request

clone:
  depth: 50

steps:
  - name: Build dfine docker image for pull request
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
      GITHUB_TOKEN_DEIM:
        from_secret: GITHUB_ACCESS_TOKEN
    settings:
      dockerfile: Dockerfile
      registry: quay.io
      repo: quay.io/logivations/ml_all
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      build_args_from_env:
        - GITHUB_TOKEN_DEIM
      cache_from:
        - quay.io/logivations/ml_all:LS_dfine_latest
        - quay.io/logivations/ml_all:LS_dfine_pr${DRONE_PULL_REQUEST}
      tags:
        - LS_dfine_pr${DRONE_PULL_REQUEST}
        - LS_dfine_pr${DRONE_PULL_REQUEST}_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD
